version: "3"

services:
  web:
    build: .
    volumes:
      - ./:/go/src/app/
      - ./go.mod:/go/src/app/go.mod
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
